const std = @import("std");

pub fn build(b: *std.Build) void {
    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{});

    const sdl2_dep = b.dependency("sdl2-compat", .{
        .target = target,
        .optimize = optimize,
    });

    const build_config_h = b.addConfigHeader(.{
        .style = .{ .cmake = sdl2_dep.path("include/SDL2/SDL_config.h.cmake") },
        .include_path = "SDL_config.h",
    }, .{
        .HAVE_CONST = 1,
        .HAVE_INLINE = 1,
        .HAVE_VOLATILE = 1,
        .HAVE_GCC_ATOMICS = 0,
        .HAVE_GCC_SYNC_LOCK_TEST_AND_SET = 0,
        .HAVE_FLOAT_H = true,
        .HAVE_STDARG_H = true,
        .HAVE_STDDEF_H = true,
        .HAVE_STDINT_H = true,
        .HAVE_LIBC = true,
        .HAVE_GETHOSTNAME = false,
        .HAVE_SETENV = false,
        .HAVE_PUTENV = false,
        .HAVE_UNSETENV = false,
        .HAVE__STRREV = false,
        .HAVE_INDEX = false,
        .HAVE_RINDEX = false,
        .HAVE_STRNSTR = false,
        .HAVE_ITOA = false,
        .HAVE__LTOA = false,
        .HAVE__UITOA = false,
        .HAVE__ULTOA = false,
        .HAVE__I64TOA = false,
        .HAVE__UI64TOA = false,
        .HAVE__COPYSIGN = false,
        .HAVE_ISINFF = false,
        .HAVE_ISNANF = false,
        .HAVE_FOPEN64 = false,
        .HAVE_FSEEKO64 = false,
        .HAVE_MEMFD_CREATE = false,
        .HAVE_SIGACTION = false,
        .HAVE_SIGTIMEDWAIT = false,
        .HAVE_SA_SIGACTION = false,
        .HAVE_SETJMP = false,
        .HAVE_SYSCTLBYNAME = false,
        .HAVE_MPROTECT = false,
        .SDL_USE_LIBICONV = false,
        .HAVE_GETAUXVAL = false,
        .HAVE_ELF_AUX_INFO = false,
        .HAVE_POLL = false,
        .HAVE_ALTIVEC_H = false,
        .HAVE_DBUS_DBUS_H = false,
        .HAVE_FCITX_H = false,
        .HAVE_IBUS_IBUS_H = false,
        .HAVE_SYS_INOTIFY_H = false,
        .HAVE_INOTIFY_INIT = false,
        .HAVE_INOTIFY_INIT1 = false,
        .HAVE_INOTIFY = false,
        .HAVE_LIBUSB = false,
        .HAVE_O_CLOEXEC = true,
        .HAVE_LIBUDEV_H = false,
        .HAVE_LIBSAMPLERATE_H = false,
        .HAVE_LIBDECOR_H = false,
        .HAVE_D3D_H = false,
        .HAVE_D3D11_H = false,
        .HAVE_D3D12_H = false,
        .HAVE_DDRAW_H = false,
        .HAVE_DSOUND_H = false,
        .HAVE_DINPUT_H = false,
        .HAVE_XINPUT_H = false,
        .HAVE_WINDOWS_GAMING_INPUT_H = false,
        .HAVE_DXGI_H = false,
        .HAVE_MMDEVICEAPI_H = false,
        .HAVE_AUDIOCLIENT_H = false,
        .HAVE_TPCSHRD_H = false,
        .HAVE_SENSORSAPI_H = false,
        .HAVE_ROAPI_H = false,
        .HAVE_SHELLSCALINGAPI_H = false,
        .USE_POSIX_SPAWN = false,
        .SDL_DEFAULT_ASSERT_LEVEL_CONFIGURED = false,
        .SDL_DEFAULT_ASSERT_LEVEL = null,
        .SDL_ATOMIC_DISABLED = false,
        .SDL_AUDIO_DISABLED = false,
        .SDL_CPUINFO_DISABLED = false,
        .SDL_EVENTS_DISABLED = false,
        .SDL_FILE_DISABLED = false,
        .SDL_JOYSTICK_DISABLED = false,
        .SDL_HAPTIC_DISABLED = false,
        .SDL_HIDAPI_DISABLED = false,
        .SDL_SENSOR_DISABLED = false,
        .SDL_LOADSO_DISABLED = false,
        .SDL_RENDER_DISABLED = false,
        .SDL_THREADS_DISABLED = false,
        .SDL_TIMERS_DISABLED = false,
        .SDL_VIDEO_DISABLED = false,
        .SDL_GPU_DISABLED = false,
        .SDL_POWER_DISABLED = false,
        .SDL_FILESYSTEM_DISABLED = false,
        .SDL_LOCALE_DISABLED = false,
        .SDL_MISC_DISABLED = false,
        .SDL_AUDIO_DRIVER_ALSA = false,
        .SDL_AUDIO_DRIVER_ALSA_DYNAMIC = "",
        .SDL_AUDIO_DRIVER_ANDROID = false,
        .SDL_AUDIO_DRIVER_OPENSLES = false,
        .SDL_AUDIO_DRIVER_AAUDIO = false,
        .SDL_AUDIO_DRIVER_ARTS = false,
        .SDL_AUDIO_DRIVER_ARTS_DYNAMIC = "",
        .SDL_AUDIO_DRIVER_COREAUDIO = false,
        .SDL_AUDIO_DRIVER_DISK = false,
        .SDL_AUDIO_DRIVER_DSOUND = false,
        .SDL_AUDIO_DRIVER_DUMMY = true,
        .SDL_AUDIO_DRIVER_EMSCRIPTEN = false,
        .SDL_AUDIO_DRIVER_ESD = false,
        .SDL_AUDIO_DRIVER_ESD_DYNAMIC = "",
        .SDL_AUDIO_DRIVER_FUSIONSOUND = false,
        .SDL_AUDIO_DRIVER_FUSIONSOUND_DYNAMIC = "",
        .SDL_AUDIO_DRIVER_HAIKU = false,
        .SDL_AUDIO_DRIVER_JACK = false,
        .SDL_AUDIO_DRIVER_JACK_DYNAMIC = "",
        .SDL_AUDIO_DRIVER_NAS = false,
        .SDL_AUDIO_DRIVER_NAS_DYNAMIC = "",
        .SDL_AUDIO_DRIVER_NETBSD = false,
        .SDL_AUDIO_DRIVER_OSS = false,
        .SDL_AUDIO_DRIVER_PAUDIO = false,
        .SDL_AUDIO_DRIVER_PIPEWIRE = false,
        .SDL_AUDIO_DRIVER_PIPEWIRE_DYNAMIC = "",
        .SDL_AUDIO_DRIVER_PULSEAUDIO = false,
        .SDL_AUDIO_DRIVER_PULSEAUDIO_DYNAMIC = "",
        .SDL_AUDIO_DRIVER_QSA = false,
        .SDL_AUDIO_DRIVER_SNDIO = false,
        .SDL_AUDIO_DRIVER_SNDIO_DYNAMIC = "",
        .SDL_AUDIO_DRIVER_SUNAUDIO = false,
        .SDL_AUDIO_DRIVER_WASAPI = false,
        .SDL_AUDIO_DRIVER_WINMM = false,
        .SDL_AUDIO_DRIVER_OS2 = false,
        .SDL_AUDIO_DRIVER_VITA = false,
        .SDL_AUDIO_DRIVER_PSP = false,
        .SDL_AUDIO_DRIVER_PS2 = false,
        .SDL_AUDIO_DRIVER_N3DS = false,
        .SDL_AUDIO_DRIVER_NGAGE = false,
        .SDL_INPUT_LINUXEV = false,
        .SDL_INPUT_LINUXKD = false,
        .SDL_INPUT_FBSDKBIO = false,
        .SDL_INPUT_WSCONS = false,
        .SDL_HAVE_MACHINE_JOYSTICK_H = false,
        .SDL_JOYSTICK_ANDROID = false,
        .SDL_JOYSTICK_DINPUT = false,
        .SDL_JOYSTICK_DUMMY = true,
        .SDL_JOYSTICK_EMSCRIPTEN = false,
        .SDL_JOYSTICK_GAMEINPUT = false,
        .SDL_JOYSTICK_HAIKU = false,
        .SDL_JOYSTICK_HIDAPI = false,
        .SDL_JOYSTICK_IOKIT = false,
        .SDL_JOYSTICK_LINUX = false,
        .SDL_JOYSTICK_MFI = false,
        .SDL_JOYSTICK_N3DS = false,
        .SDL_JOYSTICK_PS2 = false,
        .SDL_JOYSTICK_PSP = false,
        .SDL_JOYSTICK_OS2 = false,
        .SDL_JOYSTICK_RAWINPUT = false,
        .SDL_JOYSTICK_USBHID = false,
        .SDL_JOYSTICK_VIRTUAL = false,
        .SDL_JOYSTICK_VITA = false,
        .SDL_JOYSTICK_WGI = false,
        .SDL_JOYSTICK_XINPUT = false,
        .SDL_HAPTIC_DUMMY = true,
        .SDL_HAPTIC_LINUX = false,
        .SDL_HAPTIC_IOKIT = false,
        .SDL_HAPTIC_DINPUT = false,
        .SDL_HAPTIC_XINPUT = false,
        .SDL_HAPTIC_ANDROID = false,
        .SDL_LIBUSB_DYNAMIC = "",
        .SDL_UDEV_DYNAMIC = "",
        .SDL_SENSOR_ANDROID = false,
        .SDL_SENSOR_COREMOTION = false,
        .SDL_SENSOR_WINDOWS = false,
        .SDL_SENSOR_DUMMY = true,
        .SDL_SENSOR_VITA = false,
        .SDL_SENSOR_N3DS = false,
        .SDL_LOADSO_DLOPEN = false,
        .SDL_LOADSO_DUMMY = true,
        .SDL_LOADSO_LDG = false,
        .SDL_LOADSO_WINDOWS = false,
        .SDL_LOADSO_OS2 = false,
        .SDL_THREAD_GENERIC_COND_SUFFIX = false,
        .SDL_THREAD_GENERIC_RWLOCK_SUFFIX = false,
        .SDL_THREAD_PTHREAD = true,
        .SDL_THREAD_PTHREAD_RECURSIVE_MUTEX = true,
        .SDL_THREAD_PTHREAD_RECURSIVE_MUTEX_NP = false,
        .SDL_THREAD_WINDOWS = false,
        .SDL_THREAD_OS2 = false,
        .SDL_THREAD_VITA = false,
        .SDL_THREAD_PSP = false,
        .SDL_THREAD_PS2 = false,
        .SDL_THREAD_N3DS = false,
        .SDL_TIMER_DUMMY = true,
        .SDL_TIMER_HAIKU = false,
        .SDL_TIMER_UNIX = true,
        .SDL_TIMER_WINDOWS = false,
        .SDL_TIMER_OS2 = false,
        .SDL_TIMER_VITA = false,
        .SDL_TIMER_PSP = false,
        .SDL_TIMER_PS2 = false,
        .SDL_TIMER_N3DS = false,
        .SDL_VIDEO_DRIVER_ANDROID = false,
        .SDL_VIDEO_DRIVER_COCOA = false,
        .SDL_VIDEO_DRIVER_DUMMY = true,
        .SDL_VIDEO_DRIVER_EMSCRIPTEN = false,
        .SDL_VIDEO_DRIVER_HAIKU = false,
        .SDL_VIDEO_DRIVER_KMSDRM = false,
        .SDL_VIDEO_DRIVER_KMSDRM_DYNAMIC = "",
        .SDL_VIDEO_DRIVER_KMSDRM_DYNAMIC_GBM = "",
        .SDL_VIDEO_DRIVER_DIRECTFB = false,
        .SDL_VIDEO_DRIVER_DIRECTFB_DYNAMIC = "",
        .SDL_VIDEO_DRIVER_N3DS = false,
        .SDL_VIDEO_DRIVER_NGAGE = false,
        .SDL_VIDEO_DRIVER_OFFSCREEN = false,
        .SDL_VIDEO_DRIVER_PS2 = false,
        .SDL_VIDEO_DRIVER_PSP = false,
        .SDL_VIDEO_DRIVER_RISCOS = false,
        .SDL_VIDEO_DRIVER_ROCKCHIP = false,
        .SDL_VIDEO_DRIVER_RPI = false,
        .SDL_VIDEO_DRIVER_UIKIT = false,
        .SDL_VIDEO_DRIVER_VITA = false,
        .SDL_VIDEO_DRIVER_VIVANTE = false,
        .SDL_VIDEO_DRIVER_VIVANTE_VDK = false,
        .SDL_VIDEO_DRIVER_OPENVR = false,
        .SDL_VIDEO_DRIVER_WAYLAND = false,
        .SDL_VIDEO_DRIVER_WAYLAND_QT_TOUCH = false,
        .SDL_VIDEO_DRIVER_WAYLAND_DYNAMIC = "",
        .SDL_VIDEO_DRIVER_WAYLAND_DYNAMIC_CURSOR = "",
        .SDL_VIDEO_DRIVER_WAYLAND_DYNAMIC_EGL = "",
        .SDL_VIDEO_DRIVER_WAYLAND_DYNAMIC_LIBDECOR = "",
        .SDL_VIDEO_DRIVER_WAYLAND_DYNAMIC_XKBCOMMON = "",
        .SDL_VIDEO_DRIVER_WINDOWS = false,
        .SDL_VIDEO_DRIVER_WINRT = false,
        .SDL_VIDEO_DRIVER_X11 = false,
        .SDL_VIDEO_DRIVER_X11_DYNAMIC = "",
        .SDL_VIDEO_DRIVER_X11_DYNAMIC_XCURSOR = "",
        .SDL_VIDEO_DRIVER_X11_DYNAMIC_XEXT = "",
        .SDL_VIDEO_DRIVER_X11_DYNAMIC_XFIXES = "",
        .SDL_VIDEO_DRIVER_X11_DYNAMIC_XINPUT2 = "",
        .SDL_VIDEO_DRIVER_X11_DYNAMIC_XRANDR = "",
        .SDL_VIDEO_DRIVER_X11_DYNAMIC_XSS = "",
        .SDL_VIDEO_DRIVER_X11_DYNAMIC_XTEST = "",
        .SDL_VIDEO_DRIVER_X11_HAS_XKBLIB = false,
        .SDL_VIDEO_DRIVER_X11_HAS_XKBKEYCODETOKEYSYM = false,
        .SDL_VIDEO_DRIVER_X11_SUPPORTS_GENERIC_EVENTS = false,
        .SDL_VIDEO_DRIVER_X11_XCURSOR = false,
        .SDL_VIDEO_DRIVER_X11_XDBE = false,
        .SDL_VIDEO_DRIVER_X11_XFIXES = false,
        .SDL_VIDEO_DRIVER_X11_XINPUT2 = false,
        .SDL_VIDEO_DRIVER_X11_XINPUT2_SUPPORTS_MULTITOUCH = false,
        .SDL_VIDEO_DRIVER_X11_XINPUT2_SUPPORTS_SCROLLINFO = false,
        .SDL_VIDEO_DRIVER_X11_XINPUT2_SUPPORTS_GESTURE = false,
        .SDL_VIDEO_DRIVER_X11_XRANDR = false,
        .SDL_VIDEO_DRIVER_X11_XSCRNSAVER = false,
        .SDL_VIDEO_DRIVER_X11_XSHAPE = false,
        .SDL_VIDEO_DRIVER_X11_XSYNC = false,
        .SDL_VIDEO_DRIVER_X11_XTEST = false,
        .SDL_VIDEO_DRIVER_OS2 = false,
        .SDL_VIDEO_DRIVER_QNX = false,
        .SDL_VIDEO_RENDER_D3D = false,
        .SDL_VIDEO_RENDER_D3D11 = false,
        .SDL_VIDEO_RENDER_D3D12 = false,
        .SDL_VIDEO_RENDER_METAL = false,
        .SDL_VIDEO_RENDER_OGL = false,
        .SDL_VIDEO_RENDER_OGL_ES = true,
        .SDL_VIDEO_RENDER_OGL_ES2 = true,
        .SDL_VIDEO_RENDER_DIRECTFB = false,
        .SDL_VIDEO_RENDER_NGAGE = false,
        .SDL_VIDEO_RENDER_PS2 = false,
        .SDL_VIDEO_RENDER_PSP = false,
        .SDL_VIDEO_RENDER_VITA_GXM = false,
        .SDL_VIDEO_OPENGL = false,
        .SDL_VIDEO_OPENGL_ES = true,
        .SDL_VIDEO_OPENGL_ES2 = true,
        .SDL_VIDEO_OPENGL_BGL = false,
        .SDL_VIDEO_OPENGL_CGL = false,
        .SDL_VIDEO_OPENGL_GLX = false,
        .SDL_VIDEO_OPENGL_WGL = false,
        .SDL_VIDEO_OPENGL_EGL = false,
        .SDL_VIDEO_OPENGL_OSMESA = false,
        .SDL_VIDEO_OPENGL_OSMESA_DYNAMIC = "",
        .SDL_VIDEO_VULKAN = true,
        .SDL_VIDEO_METAL = false,
        .SDL_POWER_ANDROID = false,
        .SDL_POWER_LINUX = false,
        .SDL_POWER_WINDOWS = false,
        .SDL_POWER_WINRT = false,
        .SDL_POWER_MACOSX = false,
        .SDL_POWER_UIKIT = false,
        .SDL_POWER_DUMMY = true,
        .SDL_POWER_RISCOS = false,
        .SDL_POWER_HAIKU = false,
        .SDL_POWER_HARDWIRED = false,
        .SDL_POWER_EMSCRIPTEN = false,
        .SDL_POWER_OS2 = false,
        .SDL_POWER_VITA = false,
        .SDL_POWER_PSP = false,
        .SDL_POWER_N3DS = false,
        .SDL_FILESYSTEM_ANDROID = false,
        .SDL_FILESYSTEM_HAIKU = false,
        .SDL_FILESYSTEM_COCOA = false,
        .SDL_FILESYSTEM_DUMMY = false,
        .SDL_FILESYSTEM_RISCOS = false,
        .SDL_FILESYSTEM_UNIX = true,
        .SDL_FILESYSTEM_WINDOWS = false,
        .SDL_FILESYSTEM_EMSCRIPTEN = false,
        .SDL_FILESYSTEM_OS2 = false,
        .SDL_FILESYSTEM_VITA = false,
        .SDL_FILESYSTEM_PSP = false,
        .SDL_FILESYSTEM_PS2 = false,
        .SDL_FILESYSTEM_N3DS = false,
        .SDL_MISC_DUMMY = true,
        .SDL_LOCALE_DUMMY = true,
        .SDL_ALTIVEC_BLITTERS = false,
        .SDL_ARM_SIMD_BLITTERS = false,
        .SDL_ARM_NEON_BLITTERS = false,
        .DYNAPI_NEEDS_DLOPEN = true,
        .SDL_LIBSAMPLERATE_DYNAMIC = "",
        .SDL_USE_IME = false,
        .SDL_IPHONE_KEYBOARD = false,
        .SDL_IPHONE_LAUNCHSCREEN = false,
        .SDL_VIDEO_VITA_PIB = false,
        .SDL_VIDEO_VITA_PVR = false,
        .SDL_VIDEO_VITA_PVR_OGL = false,
        .SDL_HAVE_LIBDECOR_GET_MIN_MAX = false,
    });

    const libSDL2 = b.addLibrary(.{
        .name = "SDL2",
        .linkage = .static,
        .root_module = b.createModule(.{
            .target = target,
            .optimize = optimize,
            .link_libc = true,
            .sanitize_c = .off,
        }),
    });
    libSDL2.root_module.addIncludePath(sdl2_dep.path("include"));
    libSDL2.root_module.addIncludePath(sdl2_dep.path("include/SDL2"));
    libSDL2.root_module.addIncludePath(sdl2_dep.path("src"));
    {
        var files = b.addWriteFiles();
        _ = files.addCopyDirectory(sdl2_dep.path("include"), "", .{});
        _ = files.addCopyDirectory(build_config_h.getOutputDir(), "SDL2", .{});
        libSDL2.installHeadersDirectory(files.getDirectory(), "", .{});
    }
    libSDL2.root_module.addCSourceFiles(.{
        .flags = &.{
            "-fvisibility=hidden",
            "-DDECLSPEC=",
        },
        .files = &.{
            "sdl2_compat.c",
        },
        .root = b.path("src"),
    });
    libSDL2.root_module.addCSourceFiles(.{
        .flags = &.{
            "-fvisibility=hidden",
            "-DDECLSPEC=",
        },
        .files = &.{
            "SDLmain/dummy/SDL_dummy_main.c",
        },
        .root = sdl2_dep.path("src"),
    });
    b.installArtifact(libSDL2);

    const sdl_image_dep = b.dependency("SDL_image", .{});
    const libSDL_image = b.addLibrary(.{
        .name = "SDL_image",
        .linkage = .static,
        .root_module = b.createModule(.{
            .target = target,
            .optimize = optimize,
            .link_libc = true,
        }),
    });
    libSDL_image.root_module.addSystemIncludePath(libSDL2.installed_headers.items[0].getSource().path(b, "SDL2"));
    libSDL_image.root_module.addIncludePath(sdl_image_dep.path("include"));
    libSDL_image.root_module.addIncludePath(sdl_image_dep.path("src"));
    libSDL_image.installHeadersDirectory(sdl_image_dep.path("include"), "", .{});
    libSDL_image.root_module.addCSourceFiles(.{
        .flags = &.{
            "-fvisibility=hidden",
            "-DDECLSPEC=",
            "-DUSE_STBIMAGE",
            "-DLOAD_BMP",
            "-DLOAD_GIF",
            "-DLOAD_JPG",
            "-DLOAD_LBM",
            "-DLOAD_PCX",
            "-DLOAD_PNG",
            "-DLOAD_PNM",
            "-DLOAD_QOI",
            "-DLOAD_TGA",
            "-DLOAD_XCF",
            "-DLOAD_XPM",
            "-DLOAD_XV",
        },
        .files = &.{
            "IMG.c",
            "IMG_WIC.c",
            "IMG_avif.c",
            "IMG_bmp.c",
            "IMG_gif.c",
            "IMG_jpg.c",
            "IMG_jxl.c",
            "IMG_lbm.c",
            "IMG_pcx.c",
            "IMG_png.c",
            "IMG_pnm.c",
            "IMG_qoi.c",
            "IMG_stb.c",
            "IMG_svg.c",
            "IMG_tga.c",
            "IMG_tif.c",
            "IMG_webp.c",
            "IMG_xcf.c",
            "IMG_xpm.c",
            "IMG_xv.c",
        },
        .root = sdl_image_dep.path("src"),
    });
    libSDL_image.root_module.linkLibrary(libSDL2);
    b.installArtifact(libSDL_image);

    const sdl_ttf_dep = b.dependency("SDL_ttf", .{});
    const harfbuzz_enabled = b.option(bool, "enable-harfbuzz", "Use HarfBuzz to improve text shaping") orelse false;

    const libSDL_ttf = b.addLibrary(.{
        .name = "SDL_ttf",
        .linkage = .static,
        .root_module = b.createModule(.{
            .target = target,
            .optimize = optimize,
            .link_libc = true,
            .sanitize_c = .off,
        }),
    });
    libSDL_ttf.root_module.addSystemIncludePath(libSDL2.installed_headers.items[0].getSource().path(b, "SDL2"));
    libSDL_ttf.installHeader(sdl_ttf_dep.path("SDL_ttf.h"), "SDL_ttf.h");
    libSDL_ttf.root_module.addCSourceFiles(.{
        .files = &.{
            "SDL_ttf.c",
        },
        .root = sdl_ttf_dep.path(""),
    });
    if (harfbuzz_enabled) {
        const harfbuzz_dep = b.dependency("harfbuzz", .{
            .target = target,
            .optimize = optimize,
        });
        libSDL_ttf.root_module.linkLibrary(harfbuzz_dep.artifact("harfbuzz"));
        libSDL_ttf.root_module.addCMacro("TTF_USE_HARFBUZZ", "1");
    }
    const freetype_dep = b.dependency("freetype", .{
        .target = target,
        .optimize = optimize,
    });
    libSDL_ttf.root_module.linkLibrary(freetype_dep.artifact("freetype"));
    libSDL_ttf.root_module.linkLibrary(libSDL2);
    b.installArtifact(libSDL_ttf);
}
